services:
  blazorui:
    image: blazor.ui
    build: 
      context: .
      dockerfile: src/Blazor.UI/Dockerfile
    ports:
      - 5147:5147
    restart: always
    env_file: 
      - ${API_SETTINGS}
    networks:
      - mysqlcore_network
    volumes:
      - ${IMAGE_PATH}:/app/wwwroot/images


networks:
  mysqlcore_network:
    name: mysqlcore_network
    external: true