services:
  blazorui:
    image: blazor.ui
    build: 
      context: .
      dockerfile: src/Blazor.UI/Dockerfile
    ports:
      - 5147:5147
    restart: always
    env_file: 
      - env/docker-env/api-setting.dev.env
    networks:
      - mysqlcore_network


networks:
  mysqlcore_network:
    name: mysqlcore_network
    external: true