services:
  blazorui:
    image: blazor.ui
    build: 
      context: .
      dockerfile: src/Blazor.UI/Dockerfile
    ports:
      - 5147:5147
    restart: always
    env_file: 
    - env/coreapi-dev.env